on: [push]
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog
    steps:
      - name: Jira Changelog
        uses: connorsmallman/github-jira-changelog-action@1.2.0
      - name: Set Version
        run: echo ::set-env name=VERSION::1.1.1
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: connorsmallman/github-jira-changelog-action@1.2.0/actions/checkout@v1
      - name: Changelog
        id: changelog
        uses: actions/jira-changelog@v1
        with:
          jira_host: 'https://belorder.atlassian.net'
          jira_email: 'omer@belorder.com'
          jira_token: 'ATATT3xFfGF05VS0Ya0sShhQDNLpMIfySIMvQ_xnRaKAC-Nu-9lLlkjAjDbfchcnapOENDxO9KFjtF7L5oRpWnZ7WRCuKJEmpvDdAopNr4QZuHyD3SQUmkQzBDdUgvvlnCK92EUBvlDBU7TizrVKc0fy2rubLVde8xPhv_X2LSt0PqOR62g6TJc=F098AB30'
          jira_base_url: 'https://belorder.atlassian.net'
      - name: Get the changelog message
        run: echo "${{ steps.changelog.outputs.changelog_message }}"
